const collections = [
  {
    id: 1,
    label: 'Collection Alpha',
    author: 'Alpha',
    author_description: 'NFT GOD!',
    author_image: '../assets/test-author.png',
    cover_image: '../assets/test-collection-cover.png',
    description: 'Brian NFT collection by Braindom Games is a limited collection of 5,000 unique 3D NFTs with hundreds of unique attributes captured on Ethereum blockchain.',
    items: 66,
    owners: 4,
    price: 3.2,
    volume_traded: 1.3,
    website: '',
    twitter: 'https://twitter.com',
    instagram: 'https://instagram.com',
  },
  {
    id: 2,
    label: 'Collection Beta',
    author: 'Beta',
    author_description: 'NFT creator since 1898. The 1336 Coach Pop Collection commemorates the new all-time winningest coach in NBA History.',
    author_image: '../assets/test-author-2.svg',
    cover_image: '../assets/test-collection-cover-2.svg',
    description: 'Brian NFT collection is inspired by one of the most popular puzzle and brain teaser games ever - Braindom. The 1336 Coach Pop Collection commemorates the new all-time winningest coach in NBA History.',
    items: 19,
    owners: 1,
    price: 0.4,
    volume_traded: 30.04,
    website: 'https://google.com',
    twitter: '',
    instagram: 'https://instagram.com',
  },
  {
    id: 3,
    label: 'Collection Gamma',
    author: 'Gamma',
    author_description: 'Space cowboy',
    author_image: '../assets/artist-image.svg',
    cover_image: '../assets/test-collection-cover-3.svg',
    description: 'Each NFT will highlight a hand-drawn play with a digital signature from Coach Pop’s arsenal, featured against a backdrop of the different courts Spurs teams have played on during his tenure. Continuing the long-standing partnership between the Spurs & San Antonio Food Bank, 100% of the proceeds from this historic and unique collection will directly benefit the fight against hunger and feeding hope to the San Antonio and Southwest Texas community.',
    items: 84,
    owners: 44,
    price: 100.23,
    volume_traded: 20.45,
    website: '',
    twitter: 'https://twitter.com',
    instagram: '',
  },
]

export default collections